import { API_BASE_URL, AUTH_TOKEN_KEY, IS_MOCK } from '@/constants';
import { mockDelay } from '@/services/mock';
import type { ApiResponse } from '@/types';

export class ApiError extends Error {
  readonly status: number;

  constructor(message: string, status = 500) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
  }
}

export async function fetchAPI<T>(
  url: string,
  options: RequestInit = {},
): Promise<ApiResponse<T>> {
  if (IS_MOCK) {
    await mockDelay();
    return {
      success: true,
      message: 'Mock mode enabled. Response generated by the mock service layer.',
    };
  }

  const token = localStorage.getItem(AUTH_TOKEN_KEY);
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (token) {
    headers.set('Authorization', `Bearer ${token}`);
  }

  const response = await fetch(`${API_BASE_URL}${url}`, {
    ...options,
    headers,
  });

  const payload = (await response.json().catch(() => null)) as ApiResponse<T> | null;

  if (!response.ok) {
    throw new ApiError(
      payload?.error ?? `Request failed with status ${response.status}`,
      response.status,
    );
  }

  return payload ?? { success: true };
}

export function unwrapResponse<T>(response: ApiResponse<T>): T {
  if (!response.success || response.data === undefined) {
    throw new ApiError(response.error ?? 'Request failed', 400);
  }
  return response.data;
}