import { API_BASE_URL, BLOCKCHAIN_API_URL, AUTH_TOKEN_KEY, IS_MOCK } from '@/constants';
import { mockDelay } from '@/services/mock';
import type { ApiResponse } from '@/types';

export class ApiError extends Error {
  readonly status: number;

  constructor(message: string, status = 500) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
  }
}

export async function fetchAPI<T>(
  url: string,
  options: RequestInit = {},
): Promise<ApiResponse<T>> {
  if (IS_MOCK) {
    await mockDelay();
    return {
      success: true,
      message: 'Mock mode enabled. Response generated by the mock service layer.',
    };
  }

  const token = localStorage.getItem(AUTH_TOKEN_KEY);
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (token) {
    headers.set('Authorization', `Bearer ${token}`);
  }

  const response = await fetch(`${API_BASE_URL}${url}`, {
    ...options,
    headers,
  });

  const payload = (await response.json().catch(() => null)) as ApiResponse<T> | null;

  if (!response.ok) {
    throw new ApiError(
      payload?.error ?? `Request failed with status ${response.status}`,
      response.status,
    );
  }

  return payload ?? { success: true };
}

export function unwrapResponse<T>(response: ApiResponse<T>): T {
  if (!response.success || response.data === undefined) {
    throw new ApiError(response.error ?? 'Request failed', 400);
  }
  return response.data;
}

async function requestJson<T>(baseUrl: string, url: string, options: RequestInit): Promise<T> {
  const token = localStorage.getItem(AUTH_TOKEN_KEY);
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (token) {
    headers.set('Authorization', `Bearer ${token}`);
  }

  let response: Response;
  try {
    response = await fetch(`${baseUrl}${url}`, { ...options, headers });
  } catch {
    throw new ApiError('Unable to reach the service. Please check your connection and try again.', 0);
  }

  const payload = (await response.json().catch(() => null)) as {
    success: boolean;
    data?: T;
    error?: string | { code?: string; message?: string };
  } | null;

  if (!response.ok) {
    const error = payload?.error;
    const message =
      typeof error === 'string'
        ? error
        : error?.message ?? `Request failed with status ${response.status}`;
    throw new ApiError(message, response.status);
  }

  if (!payload?.success || payload.data === undefined) {
    const error = payload?.error;
    const message =
      typeof error === 'string'
        ? error
        : error?.message ?? 'The service returned an unexpected response.';
    throw new ApiError(message, response.status);
  }

  return payload.data;
}

export async function fetchBlockchainAPI<T>(
  url: string,
  options: RequestInit = {},
): Promise<T> {
  return requestJson<T>(BLOCKCHAIN_API_URL, url, options);
}