import { API_BASE_URL, BLOCKCHAIN_API_URL, AUTH_TOKEN_KEY, IS_MOCK } from '@/constants';
import { mockDelay } from '@/services/mock';
import type { ApiResponse } from '@/types';

export class ApiError extends Error {
  readonly status: number;

  constructor(message: string, status = 500) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
  }
}

export async function fetchAPI<T>(
  url: string,
  options: RequestInit = {},
): Promise<ApiResponse<T>> {
  if (IS_MOCK) {
    await mockDelay();
    return {
      success: true,
      message: 'Mock mode enabled. Response generated by the mock service layer.',
    };
  }

  const token = localStorage.getItem(AUTH_TOKEN_KEY);
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (token) {
    headers.set('Authorization', `Bearer ${token}`);
  }

  const response = await fetch(`${API_BASE_URL}${url}`, {
    ...options,
    headers,
  });

  const payload = (await response.json().catch(() => null)) as ApiResponse<T> | null;

  if (!response.ok) {
    throw new ApiError(
      payload?.error ?? `Request failed with status ${response.status}`,
      response.status,
    );
  }

  return payload ?? { success: true };
}

export function unwrapResponse<T>(response: ApiResponse<T>): T {
  if (!response.success || response.data === undefined) {
    throw new ApiError(response.error ?? 'Request failed', 400);
  }
  return response.data;
}

// Backend failure envelope (mirrors securex-blockchain src/api/middleware.ts):
// { success: false, error: <string code>, message: <human-readable>, errorCode }
interface ErrorPayload {
  success: boolean;
  error?: string | { code?: string; message?: string };
  message?: string;
  errorCode?: string;
}

function extractErrorMessage(
  payload: ErrorPayload | null,
  fallback: string,
): string {
  if (!payload) return fallback;
  const error = payload.error;
  if (typeof error === 'string') {
    // Prefer the human-readable `message` (e.g. "Issuer not found") over the
    // machine error code (e.g. "UNKNOWN_ISSUER") when both are present.
    return payload.message && payload.message !== error ? payload.message : error;
  }
  if (error?.message) return error.message;
  if (payload.message) return payload.message;
  if (payload.errorCode) return payload.errorCode;
  return fallback;
}

async function requestJson<T>(
  baseUrl: string,
  url: string,
  options: RequestInit,
  timeoutMs = 15000,
): Promise<T> {
  const token = localStorage.getItem(AUTH_TOKEN_KEY);
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (token) {
    headers.set('Authorization', `Bearer ${token}`);
  }

  const controller = new AbortController();
  const timer = window.setTimeout(() => controller.abort(), timeoutMs);

  let response: Response;
  try {
    response = await fetch(`${baseUrl}${url}`, {
      ...options,
      headers,
      signal: controller.signal,
    });
  } catch (err) {
    if (err instanceof DOMException && err.name === 'AbortError') {
      throw new ApiError('The request timed out. Please try again.', 0);
    }
    throw new ApiError(
      'Unable to reach the service. Please check your connection and try again.',
      0,
    );
  } finally {
    window.clearTimeout(timer);
  }

  const payload = (await response.json().catch(() => null)) as
    | (ErrorPayload & { data?: T })
    | null;

  if (!response.ok) {
    throw new ApiError(
      extractErrorMessage(payload, `Request failed with status ${response.status}`),
      response.status,
    );
  }

  if (!payload?.success || payload.data === undefined) {
    throw new ApiError(
      extractErrorMessage(payload, 'The service returned an unexpected response.'),
      response.status,
    );
  }

  return payload.data;
}

export async function fetchBlockchainAPI<T>(
  url: string,
  options: RequestInit = {},
): Promise<T> {
  return requestJson<T>(BLOCKCHAIN_API_URL, url, options);
}